openapi: 3.1.0
info:
  title: Bingo抽選アプリ ローカル API
  version: 0.1.0
  description: |
    React Router v7 アプリ内で shared services/localStorage を抽象化する内部 API 契約。
    画面イベントごとに以下のエンドポイントを呼び出す想定。
servers:
  - url: app://local-only
    description: ブラウザ内ローカル実装（localStorage / CSV / audio 制御）

paths:
  /session/start:
    post:
      summary: 「はじめから」でゲーム状態を初期化
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resetPrizes:
                  type: boolean
                  default: true
                  description: 景品状態も初期化するか
      responses:
        '200':
          description: 初期化後のゲーム状態
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'
  /session/resume:
    get:
      summary: 「続きから」で localStorage の状態を取得
      responses:
        '200':
          description: 復元済みゲーム状態
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStateEnvelope'
        '204':
          description: 保存済みデータが存在しない（新規開始が必要）
  /draws:
    post:
      summary: 抽選ボタン押下で新しいビンゴ番号を決定
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seed:
                  type: integer
                  description: 任意のシード（テスト用）
      responses:
        '200':
          description: 抽選結果 + 更新された状態
          content:
            application/json:
              schema:
                type: object
                required: [gameState]
                properties:
                  gameState:
                    $ref: '#/components/schemas/GameState'
        '409':
          description: 全番号が抽選済みでこれ以上抽選できない
  /history:
    get:
      summary: 直近 10 件と全履歴を取得
      responses:
        '200':
          description: 履歴ビュー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryView'
  /prizes/toggle:
    post:
      summary: 景品の当選/戻す操作
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id, selected]
              properties:
                id:
                  type: string
                selected:
                  type: boolean
      responses:
        '200':
          description: 更新後の景品リスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrizeList'
  /prizes/reorder:
    post:
      summary: DnD で並び替えた順序を保存
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [order]
              properties:
                order:
                  type: array
                  items:
                    type: string
                  description: 新しい ID 順序
      responses:
        '200':
          description: 再採番済みリスト
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrizeList'
  /prizes/import:
    post:
      summary: CSV 一括追加
    
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 取り込み結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CsvImportJob'
        '400':
          description: 必須カラム欠落または不正文字コード
  /prizes/export:
    get:
      summary: 現在の景品リストを CSV としてダウンロード
      responses:
        '200':
          description: CSV ストリーム（ダミーデータのみ共有）
          content:
            text/csv:
              schema:
                type: string
                format: binary
  /prizes:
    delete:
      summary: 一括削除（確認後に実行）
      parameters:
        - in: query
          name: confirm
          required: true
          schema:
            type: boolean
          description: UI 側で確認済みか
      responses:
        '204':
          description: 景品リストを空にし localStorage も更新完了
  /settings/bgm:
    patch:
      summary: BGM トグル / 音量設定
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BgmPreference'
      responses:
        '200':
          description: 保存後の設定
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BgmPreference'

components:
  schemas:
    DrawHistoryEntry:
      type: object
      required: [number, sequence, drawnAt]
      properties:
        number:
          type: integer
          minimum: 1
          maximum: 75
        sequence:
          type: integer
          minimum: 1
        drawnAt:
          type: string
          format: date-time
    GameState:
      type: object
      required: [drawHistory, isDrawing, createdAt, updatedAt]
      properties:
        currentNumber:
          type: integer
          nullable: true
          minimum: 1
          maximum: 75
        drawHistory:
          type: array
          items:
            $ref: '#/components/schemas/DrawHistoryEntry'
          maxItems: 75
          uniqueItems: true
        isDrawing:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    GameStateEnvelope:
      type: object
      required: [gameState, prizes, bgm]
      properties:
        gameState:
          $ref: '#/components/schemas/GameState'
        prizes:
          $ref: '#/components/schemas/PrizeList'
        bgm:
          $ref: '#/components/schemas/BgmPreference'
    Prize:
      type: object
      required: [id, order, prizeName, itemName, selected]
      properties:
        id:
          type: string
        order:
          type: integer
          minimum: 0
        prizeName:
          type: string
        itemName:
          type: string
        imagePath:
          type: string
          nullable: true
        selected:
          type: boolean
        memo:
          type: string
          nullable: true
          maxLength: 200
    PrizeList:
      type: array
      items:
        $ref: '#/components/schemas/Prize'
    BgmPreference:
      type: object
      required: [enabled, volume]
      properties:
        enabled:
          type: boolean
        volume:
          type: number
          minimum: 0
          maximum: 1
        updatedAt:
          type: string
          format: date-time
    HistoryView:
      type: object
      required: [recent, all]
      properties:
        recent:
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/DrawHistoryEntry'
        all:
          type: array
          items:
            $ref: '#/components/schemas/DrawHistoryEntry'
    CsvImportJob:
      type: object
      required: [sourceName, addedCount, skipped, processedAt]
      properties:
        sourceName:
          type: string
        addedCount:
          type: integer
          minimum: 0
        skipped:
          type: array
          items:
            type: object
            required: [id, reason]
            properties:
              id:
                type: string
              reason:
                type: string
        processedAt:
          type: string
          format: date-time
